### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by markferry** [mampfes/script.module.openhab#1]
OpenHAB 1.7.1 running on an RPi2 a reasonably complex sitemap (368 lines) takes ~50-90 seconds to display.

The timer was started when the (empty) openHAB UI frame appeared.
The timer was stopped when the sitemap items appeared in the UI frame.

Occurs consistently. (i.e. Exiting and restarting takes the same amount of time.)
After the initial sitemap page load navigation speed within the interface is normal.

**Comment by markferry** [comment]
[issue1-log.txt](https://github.com/mampfes/script.module.openhab/files/92977/issue1-log.txt)

Kodi log attached.

Thanks, Mark

**Comment by 8666** [comment]
Seems like it loads all possible items from openhab, not just those in the sitmap. Right?

**Comment by mampfes** [comment]
Please excuse the delay! The script only loads 1 sitemap, but with all sub-views. It seems that you have a large sitemap and a slow Kodi box. Sorry - there is not much that I can do.
